package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AirsupplyUser generated by hbm2java
 */
public class AirsupplyUser  implements java.io.Serializable {


     private Integer idUser;
     private Customer customer;
     private Supplier supplier;
     private TypeUser typeUser;
     private String name;
     private String surname;
     private String email;
     private String password;
     private Set<Privilege> privileges = new HashSet<Privilege>(0);

    public AirsupplyUser() {
    }

	
    public AirsupplyUser(TypeUser typeUser, String email) {
        this.typeUser = typeUser;
        this.email = email;
    }
    public AirsupplyUser(Customer customer, Supplier supplier, TypeUser typeUser, String name, String surname, String email, String password, Set<Privilege> privileges) {
       this.customer = customer;
       this.supplier = supplier;
       this.typeUser = typeUser;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.password = password;
       this.privileges = privileges;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public TypeUser getTypeUser() {
        return this.typeUser;
    }
    
    public void setTypeUser(TypeUser typeUser) {
        this.typeUser = typeUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Privilege> getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set<Privilege> privileges) {
        this.privileges = privileges;
    }




}


