package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer idAlert;
     private Customer customer;
     private Supplier supplier;
     private String descriptionAlert;
     private Set<ToBeAlert> toBeAlerts = new HashSet<ToBeAlert>(0);

    public Alert() {
    }

	
    public Alert(Customer customer, Supplier supplier) {
        this.customer = customer;
        this.supplier = supplier;
    }
    public Alert(Customer customer, Supplier supplier, String descriptionAlert, Set<ToBeAlert> toBeAlerts) {
       this.customer = customer;
       this.supplier = supplier;
       this.descriptionAlert = descriptionAlert;
       this.toBeAlerts = toBeAlerts;
    }
   
    public Integer getIdAlert() {
        return this.idAlert;
    }
    
    public void setIdAlert(Integer idAlert) {
        this.idAlert = idAlert;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getDescriptionAlert() {
        return this.descriptionAlert;
    }
    
    public void setDescriptionAlert(String descriptionAlert) {
        this.descriptionAlert = descriptionAlert;
    }
    public Set<ToBeAlert> getToBeAlerts() {
        return this.toBeAlerts;
    }
    
    public void setToBeAlerts(Set<ToBeAlert> toBeAlerts) {
        this.toBeAlerts = toBeAlerts;
    }




}


