package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CalendarAlert generated by hbm2java
 */
public class CalendarAlert  implements java.io.Serializable {


     private Date dateAlert;
     private Set<ToBeAlert> toBeAlerts = new HashSet<ToBeAlert>(0);

    public CalendarAlert() {
    }

	
    public CalendarAlert(Date dateAlert) {
        this.dateAlert = dateAlert;
    }
    public CalendarAlert(Date dateAlert, Set<ToBeAlert> toBeAlerts) {
       this.dateAlert = dateAlert;
       this.toBeAlerts = toBeAlerts;
    }
   
    public Date getDateAlert() {
        return this.dateAlert;
    }
    
    public void setDateAlert(Date dateAlert) {
        this.dateAlert = dateAlert;
    }
    public Set<ToBeAlert> getToBeAlerts() {
        return this.toBeAlerts;
    }
    
    public void setToBeAlerts(Set<ToBeAlert> toBeAlerts) {
        this.toBeAlerts = toBeAlerts;
    }




}


