package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Caracterise generated by hbm2java
 */
public class Caracterise  implements java.io.Serializable {


     private CaracteriseId id;

    public Caracterise() {
    }

    public Caracterise(CaracteriseId id) {
       this.id = id;
    }
   
    public CaracteriseId getId() {
        return this.id;
    }
    
    public void setId(CaracteriseId id) {
        this.id = id;
    }




}


