package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * CaracteriseId generated by hbm2java
 */
public class CaracteriseId  implements java.io.Serializable {


     private int idTy;
     private int idPr;

    public CaracteriseId() {
    }

    public CaracteriseId(int idTy, int idPr) {
       this.idTy = idTy;
       this.idPr = idPr;
    }
   
    public int getIdTy() {
        return this.idTy;
    }
    
    public void setIdTy(int idTy) {
        this.idTy = idTy;
    }
    public int getIdPr() {
        return this.idPr;
    }
    
    public void setIdPr(int idPr) {
        this.idPr = idPr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaracteriseId) ) return false;
		 CaracteriseId castOther = ( CaracteriseId ) other; 
         
		 return (this.getIdTy()==castOther.getIdTy())
 && (this.getIdPr()==castOther.getIdPr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTy();
         result = 37 * result + this.getIdPr();
         return result;
   }   


}


