package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int idC;
     private String nameC;
     private String streetC;
     private String zipC;
     private String cityC;
     private String countrycodeC;

    public Customer() {
    }

	
    public Customer(int idC) {
        this.idC = idC;
    }
    public Customer(int idC, String nameC, String streetC, String zipC, String cityC, String countrycodeC) {
       this.idC = idC;
       this.nameC = nameC;
       this.streetC = streetC;
       this.zipC = zipC;
       this.cityC = cityC;
       this.countrycodeC = countrycodeC;
    }
   
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public String getNameC() {
        return this.nameC;
    }
    
    public void setNameC(String nameC) {
        this.nameC = nameC;
    }
    public String getStreetC() {
        return this.streetC;
    }
    
    public void setStreetC(String streetC) {
        this.streetC = streetC;
    }
    public String getZipC() {
        return this.zipC;
    }
    
    public void setZipC(String zipC) {
        this.zipC = zipC;
    }
    public String getCityC() {
        return this.cityC;
    }
    
    public void setCityC(String cityC) {
        this.cityC = cityC;
    }
    public String getCountrycodeC() {
        return this.countrycodeC;
    }
    
    public void setCountrycodeC(String countrycodeC) {
        this.countrycodeC = countrycodeC;
    }




}


