package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int idC;
     private String nameC;
     private String streetC;
     private String zipC;
     private String cityC;
     private String countrycodeC;
     private Set<Po> pos = new HashSet<Po>(0);
     private Set<AirsupplyUser> airsupplyUsers = new HashSet<AirsupplyUser>(0);
     private Set<Alert> alerts = new HashSet<Alert>(0);
     private Set<MaterialVmi2> materialVmi2s = new HashSet<MaterialVmi2>(0);
     private Set<CustomerVmi> customerVmis = new HashSet<CustomerVmi>(0);

    public Customer() {
    }

	
    public Customer(int idC) {
        this.idC = idC;
    }
    public Customer(int idC, String nameC, String streetC, String zipC, String cityC, String countrycodeC, Set<Po> pos, Set<AirsupplyUser> airsupplyUsers, Set<Alert> alerts, Set<MaterialVmi2> materialVmi2s, Set<CustomerVmi> customerVmis) {
       this.idC = idC;
       this.nameC = nameC;
       this.streetC = streetC;
       this.zipC = zipC;
       this.cityC = cityC;
       this.countrycodeC = countrycodeC;
       this.pos = pos;
       this.airsupplyUsers = airsupplyUsers;
       this.alerts = alerts;
       this.materialVmi2s = materialVmi2s;
       this.customerVmis = customerVmis;
    }
   
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public String getNameC() {
        return this.nameC;
    }
    
    public void setNameC(String nameC) {
        this.nameC = nameC;
    }
    public String getStreetC() {
        return this.streetC;
    }
    
    public void setStreetC(String streetC) {
        this.streetC = streetC;
    }
    public String getZipC() {
        return this.zipC;
    }
    
    public void setZipC(String zipC) {
        this.zipC = zipC;
    }
    public String getCityC() {
        return this.cityC;
    }
    
    public void setCityC(String cityC) {
        this.cityC = cityC;
    }
    public String getCountrycodeC() {
        return this.countrycodeC;
    }
    
    public void setCountrycodeC(String countrycodeC) {
        this.countrycodeC = countrycodeC;
    }
    public Set<Po> getPos() {
        return this.pos;
    }
    
    public void setPos(Set<Po> pos) {
        this.pos = pos;
    }
    public Set<AirsupplyUser> getAirsupplyUsers() {
        return this.airsupplyUsers;
    }
    
    public void setAirsupplyUsers(Set<AirsupplyUser> airsupplyUsers) {
        this.airsupplyUsers = airsupplyUsers;
    }
    public Set<Alert> getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set<Alert> alerts) {
        this.alerts = alerts;
    }
    public Set<MaterialVmi2> getMaterialVmi2s() {
        return this.materialVmi2s;
    }
    
    public void setMaterialVmi2s(Set<MaterialVmi2> materialVmi2s) {
        this.materialVmi2s = materialVmi2s;
    }
    public Set<CustomerVmi> getCustomerVmis() {
        return this.customerVmis;
    }
    
    public void setCustomerVmis(Set<CustomerVmi> customerVmis) {
        this.customerVmis = customerVmis;
    }




}


