package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * CustomerVmi generated by hbm2java
 */
public class CustomerVmi  implements java.io.Serializable {


     private int shipIdC;
     private int idC;
     private String shipName1;
     private String shipName3;
     private String shipStreet;
     private String shipZipCode;
     private String shipCity;
     private String shipCountryCode;

    public CustomerVmi() {
    }

	
    public CustomerVmi(int shipIdC, int idC) {
        this.shipIdC = shipIdC;
        this.idC = idC;
    }
    public CustomerVmi(int shipIdC, int idC, String shipName1, String shipName3, String shipStreet, String shipZipCode, String shipCity, String shipCountryCode) {
       this.shipIdC = shipIdC;
       this.idC = idC;
       this.shipName1 = shipName1;
       this.shipName3 = shipName3;
       this.shipStreet = shipStreet;
       this.shipZipCode = shipZipCode;
       this.shipCity = shipCity;
       this.shipCountryCode = shipCountryCode;
    }
   
    public int getShipIdC() {
        return this.shipIdC;
    }
    
    public void setShipIdC(int shipIdC) {
        this.shipIdC = shipIdC;
    }
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public String getShipName1() {
        return this.shipName1;
    }
    
    public void setShipName1(String shipName1) {
        this.shipName1 = shipName1;
    }
    public String getShipName3() {
        return this.shipName3;
    }
    
    public void setShipName3(String shipName3) {
        this.shipName3 = shipName3;
    }
    public String getShipStreet() {
        return this.shipStreet;
    }
    
    public void setShipStreet(String shipStreet) {
        this.shipStreet = shipStreet;
    }
    public String getShipZipCode() {
        return this.shipZipCode;
    }
    
    public void setShipZipCode(String shipZipCode) {
        this.shipZipCode = shipZipCode;
    }
    public String getShipCity() {
        return this.shipCity;
    }
    
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity;
    }
    public String getShipCountryCode() {
        return this.shipCountryCode;
    }
    
    public void setShipCountryCode(String shipCountryCode) {
        this.shipCountryCode = shipCountryCode;
    }




}


