package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * HasA generated by hbm2java
 */
public class HasA  implements java.io.Serializable {


     private HasAId id;
     private ModificationCalendar modificationCalendar;
     private PoLine poLine;
     private Status status;
     private String commentary;

    public HasA() {
    }

	
    public HasA(HasAId id, ModificationCalendar modificationCalendar, PoLine poLine, Status status) {
        this.id = id;
        this.modificationCalendar = modificationCalendar;
        this.poLine = poLine;
        this.status = status;
    }
    public HasA(HasAId id, ModificationCalendar modificationCalendar, PoLine poLine, Status status, String commentary) {
       this.id = id;
       this.modificationCalendar = modificationCalendar;
       this.poLine = poLine;
       this.status = status;
       this.commentary = commentary;
    }
   
    public HasAId getId() {
        return this.id;
    }
    
    public void setId(HasAId id) {
        this.id = id;
    }
    public ModificationCalendar getModificationCalendar() {
        return this.modificationCalendar;
    }
    
    public void setModificationCalendar(ModificationCalendar modificationCalendar) {
        this.modificationCalendar = modificationCalendar;
    }
    public PoLine getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(PoLine poLine) {
        this.poLine = poLine;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }




}


