package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HasAId generated by hbm2java
 */
public class HasAId  implements java.io.Serializable {


     private String poLineId;
     private int idStatus;
     private Date lastModDate;

    public HasAId() {
    }

    public HasAId(String poLineId, int idStatus, Date lastModDate) {
       this.poLineId = poLineId;
       this.idStatus = idStatus;
       this.lastModDate = lastModDate;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public int getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }
    public Date getLastModDate() {
        return this.lastModDate;
    }
    
    public void setLastModDate(Date lastModDate) {
        this.lastModDate = lastModDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HasAId) ) return false;
		 HasAId castOther = ( HasAId ) other; 
         
		 return ( (this.getPoLineId()==castOther.getPoLineId()) || ( this.getPoLineId()!=null && castOther.getPoLineId()!=null && this.getPoLineId().equals(castOther.getPoLineId()) ) )
 && (this.getIdStatus()==castOther.getIdStatus())
 && ( (this.getLastModDate()==castOther.getLastModDate()) || ( this.getLastModDate()!=null && castOther.getLastModDate()!=null && this.getLastModDate().equals(castOther.getLastModDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPoLineId() == null ? 0 : this.getPoLineId().hashCode() );
         result = 37 * result + this.getIdStatus();
         result = 37 * result + ( getLastModDate() == null ? 0 : this.getLastModDate().hashCode() );
         return result;
   }   


}


