package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * HasA generated by hbm2java
 */
public class HasA  implements java.io.Serializable {


     private HasAId id;
     private String commentary;

    public HasA() {
    }

	
    public HasA(HasAId id) {
        this.id = id;
    }
    public HasA(HasAId id, String commentary) {
       this.id = id;
       this.commentary = commentary;
    }
   
    public HasAId getId() {
        return this.id;
    }
    
    public void setId(HasAId id) {
        this.id = id;
    }
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }




}


