package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * MaterialVmiId generated by hbm2java
 */
public class MaterialVmiId  implements java.io.Serializable {


     private String idCmVmi;
     private String idSmVmi;

    public MaterialVmiId() {
    }

    public MaterialVmiId(String idCmVmi, String idSmVmi) {
       this.idCmVmi = idCmVmi;
       this.idSmVmi = idSmVmi;
    }
   
    public String getIdCmVmi() {
        return this.idCmVmi;
    }
    
    public void setIdCmVmi(String idCmVmi) {
        this.idCmVmi = idCmVmi;
    }
    public String getIdSmVmi() {
        return this.idSmVmi;
    }
    
    public void setIdSmVmi(String idSmVmi) {
        this.idSmVmi = idSmVmi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialVmiId) ) return false;
		 MaterialVmiId castOther = ( MaterialVmiId ) other; 
         
		 return ( (this.getIdCmVmi()==castOther.getIdCmVmi()) || ( this.getIdCmVmi()!=null && castOther.getIdCmVmi()!=null && this.getIdCmVmi().equals(castOther.getIdCmVmi()) ) )
 && ( (this.getIdSmVmi()==castOther.getIdSmVmi()) || ( this.getIdSmVmi()!=null && castOther.getIdSmVmi()!=null && this.getIdSmVmi().equals(castOther.getIdSmVmi()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCmVmi() == null ? 0 : this.getIdCmVmi().hashCode() );
         result = 37 * result + ( getIdSmVmi() == null ? 0 : this.getIdSmVmi().hashCode() );
         return result;
   }   


}


