package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * MaterialVmi2 generated by hbm2java
 */
public class MaterialVmi2  implements java.io.Serializable {


     private MaterialVmi2Id id;
     private Customer customer;
     private MaterialVmi materialVmi;
     private StockUpdateDate stockUpdateDate;
     private Supplier supplier;
     private VmiItem vmiItem;
     private String unitOfMeasure;
     private Integer minStock;
     private Integer maxStock;
     private String quantity;

    public MaterialVmi2() {
    }

	
    public MaterialVmi2(MaterialVmi2Id id, Customer customer, MaterialVmi materialVmi, StockUpdateDate stockUpdateDate, Supplier supplier, VmiItem vmiItem) {
        this.id = id;
        this.customer = customer;
        this.materialVmi = materialVmi;
        this.stockUpdateDate = stockUpdateDate;
        this.supplier = supplier;
        this.vmiItem = vmiItem;
    }
    public MaterialVmi2(MaterialVmi2Id id, Customer customer, MaterialVmi materialVmi, StockUpdateDate stockUpdateDate, Supplier supplier, VmiItem vmiItem, String unitOfMeasure, Integer minStock, Integer maxStock, String quantity) {
       this.id = id;
       this.customer = customer;
       this.materialVmi = materialVmi;
       this.stockUpdateDate = stockUpdateDate;
       this.supplier = supplier;
       this.vmiItem = vmiItem;
       this.unitOfMeasure = unitOfMeasure;
       this.minStock = minStock;
       this.maxStock = maxStock;
       this.quantity = quantity;
    }
   
    public MaterialVmi2Id getId() {
        return this.id;
    }
    
    public void setId(MaterialVmi2Id id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public MaterialVmi getMaterialVmi() {
        return this.materialVmi;
    }
    
    public void setMaterialVmi(MaterialVmi materialVmi) {
        this.materialVmi = materialVmi;
    }
    public StockUpdateDate getStockUpdateDate() {
        return this.stockUpdateDate;
    }
    
    public void setStockUpdateDate(StockUpdateDate stockUpdateDate) {
        this.stockUpdateDate = stockUpdateDate;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public VmiItem getVmiItem() {
        return this.vmiItem;
    }
    
    public void setVmiItem(VmiItem vmiItem) {
        this.vmiItem = vmiItem;
    }
    public String getUnitOfMeasure() {
        return this.unitOfMeasure;
    }
    
    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }
    public Integer getMinStock() {
        return this.minStock;
    }
    
    public void setMinStock(Integer minStock) {
        this.minStock = minStock;
    }
    public Integer getMaxStock() {
        return this.maxStock;
    }
    
    public void setMaxStock(Integer maxStock) {
        this.maxStock = maxStock;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }




}


