package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * MaterialVmi generated by hbm2java
 */
public class MaterialVmi  implements java.io.Serializable {


     private MaterialVmiId id;
     private String descritpionCmVmi;
     private String descriptionSmVmi;
     private Double netPrice;
     private String currency;
     private String payementTerms;

    public MaterialVmi() {
    }

	
    public MaterialVmi(MaterialVmiId id) {
        this.id = id;
    }
    public MaterialVmi(MaterialVmiId id, String descritpionCmVmi, String descriptionSmVmi, Double netPrice, String currency, String payementTerms) {
       this.id = id;
       this.descritpionCmVmi = descritpionCmVmi;
       this.descriptionSmVmi = descriptionSmVmi;
       this.netPrice = netPrice;
       this.currency = currency;
       this.payementTerms = payementTerms;
    }
   
    public MaterialVmiId getId() {
        return this.id;
    }
    
    public void setId(MaterialVmiId id) {
        this.id = id;
    }
    public String getDescritpionCmVmi() {
        return this.descritpionCmVmi;
    }
    
    public void setDescritpionCmVmi(String descritpionCmVmi) {
        this.descritpionCmVmi = descritpionCmVmi;
    }
    public String getDescriptionSmVmi() {
        return this.descriptionSmVmi;
    }
    
    public void setDescriptionSmVmi(String descriptionSmVmi) {
        this.descriptionSmVmi = descriptionSmVmi;
    }
    public Double getNetPrice() {
        return this.netPrice;
    }
    
    public void setNetPrice(Double netPrice) {
        this.netPrice = netPrice;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getPayementTerms() {
        return this.payementTerms;
    }
    
    public void setPayementTerms(String payementTerms) {
        this.payementTerms = payementTerms;
    }




}


