package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MaterialVmi2Id generated by hbm2java
 */
public class MaterialVmi2Id  implements java.io.Serializable {


     private Date updateDate;
     private String referenceItem;
     private String idCmVmi;
     private String idSmVmi;
     private String idS;
     private int idC;

    public MaterialVmi2Id() {
    }

    public MaterialVmi2Id(Date updateDate, String referenceItem, String idCmVmi, String idSmVmi, String idS, int idC) {
       this.updateDate = updateDate;
       this.referenceItem = referenceItem;
       this.idCmVmi = idCmVmi;
       this.idSmVmi = idSmVmi;
       this.idS = idS;
       this.idC = idC;
    }
   
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getReferenceItem() {
        return this.referenceItem;
    }
    
    public void setReferenceItem(String referenceItem) {
        this.referenceItem = referenceItem;
    }
    public String getIdCmVmi() {
        return this.idCmVmi;
    }
    
    public void setIdCmVmi(String idCmVmi) {
        this.idCmVmi = idCmVmi;
    }
    public String getIdSmVmi() {
        return this.idSmVmi;
    }
    
    public void setIdSmVmi(String idSmVmi) {
        this.idSmVmi = idSmVmi;
    }
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialVmi2Id) ) return false;
		 MaterialVmi2Id castOther = ( MaterialVmi2Id ) other; 
         
		 return ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getReferenceItem()==castOther.getReferenceItem()) || ( this.getReferenceItem()!=null && castOther.getReferenceItem()!=null && this.getReferenceItem().equals(castOther.getReferenceItem()) ) )
 && ( (this.getIdCmVmi()==castOther.getIdCmVmi()) || ( this.getIdCmVmi()!=null && castOther.getIdCmVmi()!=null && this.getIdCmVmi().equals(castOther.getIdCmVmi()) ) )
 && ( (this.getIdSmVmi()==castOther.getIdSmVmi()) || ( this.getIdSmVmi()!=null && castOther.getIdSmVmi()!=null && this.getIdSmVmi().equals(castOther.getIdSmVmi()) ) )
 && ( (this.getIdS()==castOther.getIdS()) || ( this.getIdS()!=null && castOther.getIdS()!=null && this.getIdS().equals(castOther.getIdS()) ) )
 && (this.getIdC()==castOther.getIdC());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getReferenceItem() == null ? 0 : this.getReferenceItem().hashCode() );
         result = 37 * result + ( getIdCmVmi() == null ? 0 : this.getIdCmVmi().hashCode() );
         result = 37 * result + ( getIdSmVmi() == null ? 0 : this.getIdSmVmi().hashCode() );
         result = 37 * result + ( getIdS() == null ? 0 : this.getIdS().hashCode() );
         result = 37 * result + this.getIdC();
         return result;
   }   


}


