package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * MaterialId generated by hbm2java
 */
public class MaterialId  implements java.io.Serializable {


     private String idCm;
     private String idSm;

    public MaterialId() {
    }

    public MaterialId(String idCm, String idSm) {
       this.idCm = idCm;
       this.idSm = idSm;
    }
   
    public String getIdCm() {
        return this.idCm;
    }
    
    public void setIdCm(String idCm) {
        this.idCm = idCm;
    }
    public String getIdSm() {
        return this.idSm;
    }
    
    public void setIdSm(String idSm) {
        this.idSm = idSm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialId) ) return false;
		 MaterialId castOther = ( MaterialId ) other; 
         
		 return ( (this.getIdCm()==castOther.getIdCm()) || ( this.getIdCm()!=null && castOther.getIdCm()!=null && this.getIdCm().equals(castOther.getIdCm()) ) )
 && ( (this.getIdSm()==castOther.getIdSm()) || ( this.getIdSm()!=null && castOther.getIdSm()!=null && this.getIdSm().equals(castOther.getIdSm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCm() == null ? 0 : this.getIdCm().hashCode() );
         result = 37 * result + ( getIdSm() == null ? 0 : this.getIdSm().hashCode() );
         return result;
   }   


}


