package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private MaterialId id;
     private String descriptionCm;
     private String descriptionSm;
     private String unitOfMeasure;
     private Set<PoLine> poLines = new HashSet<PoLine>(0);

    public Material() {
    }

	
    public Material(MaterialId id) {
        this.id = id;
    }
    public Material(MaterialId id, String descriptionCm, String descriptionSm, String unitOfMeasure, Set<PoLine> poLines) {
       this.id = id;
       this.descriptionCm = descriptionCm;
       this.descriptionSm = descriptionSm;
       this.unitOfMeasure = unitOfMeasure;
       this.poLines = poLines;
    }
   
    public MaterialId getId() {
        return this.id;
    }
    
    public void setId(MaterialId id) {
        this.id = id;
    }
    public String getDescriptionCm() {
        return this.descriptionCm;
    }
    
    public void setDescriptionCm(String descriptionCm) {
        this.descriptionCm = descriptionCm;
    }
    public String getDescriptionSm() {
        return this.descriptionSm;
    }
    
    public void setDescriptionSm(String descriptionSm) {
        this.descriptionSm = descriptionSm;
    }
    public String getUnitOfMeasure() {
        return this.unitOfMeasure;
    }
    
    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }
    public Set<PoLine> getPoLines() {
        return this.poLines;
    }
    
    public void setPoLines(Set<PoLine> poLines) {
        this.poLines = poLines;
    }




}


