package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MaterialVmi generated by hbm2java
 */
public class MaterialVmi  implements java.io.Serializable {


     private MaterialVmiId id;
     private String descritpionCmVmi;
     private String descriptionSmVmi;
     private Double netPrice;
     private String currency;
     private String payementTerms;
     private Set<MaterialVmi2> materialVmi2s = new HashSet<MaterialVmi2>(0);

    public MaterialVmi() {
    }

	
    public MaterialVmi(MaterialVmiId id) {
        this.id = id;
    }
    public MaterialVmi(MaterialVmiId id, String descritpionCmVmi, String descriptionSmVmi, Double netPrice, String currency, String payementTerms, Set<MaterialVmi2> materialVmi2s) {
       this.id = id;
       this.descritpionCmVmi = descritpionCmVmi;
       this.descriptionSmVmi = descriptionSmVmi;
       this.netPrice = netPrice;
       this.currency = currency;
       this.payementTerms = payementTerms;
       this.materialVmi2s = materialVmi2s;
    }
   
    public MaterialVmiId getId() {
        return this.id;
    }
    
    public void setId(MaterialVmiId id) {
        this.id = id;
    }
    public String getDescritpionCmVmi() {
        return this.descritpionCmVmi;
    }
    
    public void setDescritpionCmVmi(String descritpionCmVmi) {
        this.descritpionCmVmi = descritpionCmVmi;
    }
    public String getDescriptionSmVmi() {
        return this.descriptionSmVmi;
    }
    
    public void setDescriptionSmVmi(String descriptionSmVmi) {
        this.descriptionSmVmi = descriptionSmVmi;
    }
    public Double getNetPrice() {
        return this.netPrice;
    }
    
    public void setNetPrice(Double netPrice) {
        this.netPrice = netPrice;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getPayementTerms() {
        return this.payementTerms;
    }
    
    public void setPayementTerms(String payementTerms) {
        this.payementTerms = payementTerms;
    }
    public Set<MaterialVmi2> getMaterialVmi2s() {
        return this.materialVmi2s;
    }
    
    public void setMaterialVmi2s(Set<MaterialVmi2> materialVmi2s) {
        this.materialVmi2s = materialVmi2s;
    }




}


