package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private MaterialId id;
     private String descriptionCm;
     private String descriptionSm;
     private String unitOfMeasure;

    public Material() {
    }

	
    public Material(MaterialId id) {
        this.id = id;
    }
    public Material(MaterialId id, String descriptionCm, String descriptionSm, String unitOfMeasure) {
       this.id = id;
       this.descriptionCm = descriptionCm;
       this.descriptionSm = descriptionSm;
       this.unitOfMeasure = unitOfMeasure;
    }
   
    public MaterialId getId() {
        return this.id;
    }
    
    public void setId(MaterialId id) {
        this.id = id;
    }
    public String getDescriptionCm() {
        return this.descriptionCm;
    }
    
    public void setDescriptionCm(String descriptionCm) {
        this.descriptionCm = descriptionCm;
    }
    public String getDescriptionSm() {
        return this.descriptionSm;
    }
    
    public void setDescriptionSm(String descriptionSm) {
        this.descriptionSm = descriptionSm;
    }
    public String getUnitOfMeasure() {
        return this.unitOfMeasure;
    }
    
    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }




}


