package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ModificationCalendar generated by hbm2java
 */
public class ModificationCalendar  implements java.io.Serializable {


     private Date lastModDate;
     private Set<HasA> hasAs = new HashSet<HasA>(0);

    public ModificationCalendar() {
    }

	
    public ModificationCalendar(Date lastModDate) {
        this.lastModDate = lastModDate;
    }
    public ModificationCalendar(Date lastModDate, Set<HasA> hasAs) {
       this.lastModDate = lastModDate;
       this.hasAs = hasAs;
    }
   
    public Date getLastModDate() {
        return this.lastModDate;
    }
    
    public void setLastModDate(Date lastModDate) {
        this.lastModDate = lastModDate;
    }
    public Set<HasA> getHasAs() {
        return this.hasAs;
    }
    
    public void setHasAs(Set<HasA> hasAs) {
        this.hasAs = hasAs;
    }




}


