package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ModificationCalendar generated by hbm2java
 */
public class ModificationCalendar  implements java.io.Serializable {


     private Date lastModDate;

    public ModificationCalendar() {
    }

    public ModificationCalendar(Date lastModDate) {
       this.lastModDate = lastModDate;
    }
   
    public Date getLastModDate() {
        return this.lastModDate;
    }
    
    public void setLastModDate(Date lastModDate) {
        this.lastModDate = lastModDate;
    }




}


