package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int idPayment;
     private String description;
     private Set<Po> pos = new HashSet<Po>(0);

    public Payment() {
    }

	
    public Payment(int idPayment) {
        this.idPayment = idPayment;
    }
    public Payment(int idPayment, String description, Set<Po> pos) {
       this.idPayment = idPayment;
       this.description = description;
       this.pos = pos;
    }
   
    public int getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(int idPayment) {
        this.idPayment = idPayment;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Po> getPos() {
        return this.pos;
    }
    
    public void setPos(Set<Po> pos) {
        this.pos = pos;
    }




}


