package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Po generated by hbm2java
 */
public class Po  implements java.io.Serializable {


     private String poNumber;
     private int idPayment;
     private int idC;
     private Date publicationDate;
     private String documentType;
     private Date erpCreationDate;
     private String currency;

    public Po() {
    }

	
    public Po(String poNumber, int idPayment, int idC) {
        this.poNumber = poNumber;
        this.idPayment = idPayment;
        this.idC = idC;
    }
    public Po(String poNumber, int idPayment, int idC, Date publicationDate, String documentType, Date erpCreationDate, String currency) {
       this.poNumber = poNumber;
       this.idPayment = idPayment;
       this.idC = idC;
       this.publicationDate = publicationDate;
       this.documentType = documentType;
       this.erpCreationDate = erpCreationDate;
       this.currency = currency;
    }
   
    public String getPoNumber() {
        return this.poNumber;
    }
    
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }
    public int getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(int idPayment) {
        this.idPayment = idPayment;
    }
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public Date getErpCreationDate() {
        return this.erpCreationDate;
    }
    
    public void setErpCreationDate(Date erpCreationDate) {
        this.erpCreationDate = erpCreationDate;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


