package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Po generated by hbm2java
 */
public class Po  implements java.io.Serializable {


     private String poNumber;
     private Customer customer;
     private Payment payment;
     private Date publicationDate;
     private String documentType;
     private Date erpCreationDate;
     private String currency;
     private Set<PoLine> poLines = new HashSet<PoLine>(0);

    public Po() {
    }

	
    public Po(String poNumber, Customer customer, Payment payment) {
        this.poNumber = poNumber;
        this.customer = customer;
        this.payment = payment;
    }
    public Po(String poNumber, Customer customer, Payment payment, Date publicationDate, String documentType, Date erpCreationDate, String currency, Set<PoLine> poLines) {
       this.poNumber = poNumber;
       this.customer = customer;
       this.payment = payment;
       this.publicationDate = publicationDate;
       this.documentType = documentType;
       this.erpCreationDate = erpCreationDate;
       this.currency = currency;
       this.poLines = poLines;
    }
   
    public String getPoNumber() {
        return this.poNumber;
    }
    
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public Date getErpCreationDate() {
        return this.erpCreationDate;
    }
    
    public void setErpCreationDate(Date erpCreationDate) {
        this.erpCreationDate = erpCreationDate;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public Set<PoLine> getPoLines() {
        return this.poLines;
    }
    
    public void setPoLines(Set<PoLine> poLines) {
        this.poLines = poLines;
    }




}


