package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoLine generated by hbm2java
 */
public class PoLine  implements java.io.Serializable {


     private String poLineId;
     private Material material;
     private Po po;
     private String poLineNumber;
     private Date creationDate;
     private Set<Price> prices = new HashSet<Price>(0);
     private Set<Promised> promiseds = new HashSet<Promised>(0);
     private Set<ToBeAlert> toBeAlerts = new HashSet<ToBeAlert>(0);
     private Set<HasA> hasAs = new HashSet<HasA>(0);
     private Set<Received> receiveds = new HashSet<Received>(0);
     private Set<Requested> requesteds = new HashSet<Requested>(0);

    public PoLine() {
    }

	
    public PoLine(String poLineId, Material material, Po po) {
        this.poLineId = poLineId;
        this.material = material;
        this.po = po;
    }
    public PoLine(String poLineId, Material material, Po po, String poLineNumber, Date creationDate, Set<Price> prices, Set<Promised> promiseds, Set<ToBeAlert> toBeAlerts, Set<HasA> hasAs, Set<Received> receiveds, Set<Requested> requesteds) {
       this.poLineId = poLineId;
       this.material = material;
       this.po = po;
       this.poLineNumber = poLineNumber;
       this.creationDate = creationDate;
       this.prices = prices;
       this.promiseds = promiseds;
       this.toBeAlerts = toBeAlerts;
       this.hasAs = hasAs;
       this.receiveds = receiveds;
       this.requesteds = requesteds;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Po getPo() {
        return this.po;
    }
    
    public void setPo(Po po) {
        this.po = po;
    }
    public String getPoLineNumber() {
        return this.poLineNumber;
    }
    
    public void setPoLineNumber(String poLineNumber) {
        this.poLineNumber = poLineNumber;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Set<Price> getPrices() {
        return this.prices;
    }
    
    public void setPrices(Set<Price> prices) {
        this.prices = prices;
    }
    public Set<Promised> getPromiseds() {
        return this.promiseds;
    }
    
    public void setPromiseds(Set<Promised> promiseds) {
        this.promiseds = promiseds;
    }
    public Set<ToBeAlert> getToBeAlerts() {
        return this.toBeAlerts;
    }
    
    public void setToBeAlerts(Set<ToBeAlert> toBeAlerts) {
        this.toBeAlerts = toBeAlerts;
    }
    public Set<HasA> getHasAs() {
        return this.hasAs;
    }
    
    public void setHasAs(Set<HasA> hasAs) {
        this.hasAs = hasAs;
    }
    public Set<Received> getReceiveds() {
        return this.receiveds;
    }
    
    public void setReceiveds(Set<Received> receiveds) {
        this.receiveds = receiveds;
    }
    public Set<Requested> getRequesteds() {
        return this.requesteds;
    }
    
    public void setRequesteds(Set<Requested> requesteds) {
        this.requesteds = requesteds;
    }




}


