package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PoLine generated by hbm2java
 */
public class PoLine  implements java.io.Serializable {


     private String poLineId;
     private String idCm;
     private String idSm;
     private String poNumber;
     private String poLineNumber;
     private Date creationDate;

    public PoLine() {
    }

	
    public PoLine(String poLineId, String idCm, String idSm, String poNumber) {
        this.poLineId = poLineId;
        this.idCm = idCm;
        this.idSm = idSm;
        this.poNumber = poNumber;
    }
    public PoLine(String poLineId, String idCm, String idSm, String poNumber, String poLineNumber, Date creationDate) {
       this.poLineId = poLineId;
       this.idCm = idCm;
       this.idSm = idSm;
       this.poNumber = poNumber;
       this.poLineNumber = poLineNumber;
       this.creationDate = creationDate;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public String getIdCm() {
        return this.idCm;
    }
    
    public void setIdCm(String idCm) {
        this.idCm = idCm;
    }
    public String getIdSm() {
        return this.idSm;
    }
    
    public void setIdSm(String idSm) {
        this.idSm = idSm;
    }
    public String getPoNumber() {
        return this.poNumber;
    }
    
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }
    public String getPoLineNumber() {
        return this.poLineNumber;
    }
    
    public void setPoLineNumber(String poLineNumber) {
        this.poLineNumber = poLineNumber;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


