package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Price generated by hbm2java
 */
public class Price  implements java.io.Serializable {


     private PriceId id;
     private Double oringialPrice;
     private Double price;

    public Price() {
    }

	
    public Price(PriceId id) {
        this.id = id;
    }
    public Price(PriceId id, Double oringialPrice, Double price) {
       this.id = id;
       this.oringialPrice = oringialPrice;
       this.price = price;
    }
   
    public PriceId getId() {
        return this.id;
    }
    
    public void setId(PriceId id) {
        this.id = id;
    }
    public Double getOringialPrice() {
        return this.oringialPrice;
    }
    
    public void setOringialPrice(Double oringialPrice) {
        this.oringialPrice = oringialPrice;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


