package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PriceCalendar generated by hbm2java
 */
public class PriceCalendar  implements java.io.Serializable {


     private Date priceDate;
     private Set<Price> prices = new HashSet<Price>(0);

    public PriceCalendar() {
    }

	
    public PriceCalendar(Date priceDate) {
        this.priceDate = priceDate;
    }
    public PriceCalendar(Date priceDate, Set<Price> prices) {
       this.priceDate = priceDate;
       this.prices = prices;
    }
   
    public Date getPriceDate() {
        return this.priceDate;
    }
    
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }
    public Set<Price> getPrices() {
        return this.prices;
    }
    
    public void setPrices(Set<Price> prices) {
        this.prices = prices;
    }




}


