package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PriceCalendar generated by hbm2java
 */
public class PriceCalendar  implements java.io.Serializable {


     private Date priceDate;

    public PriceCalendar() {
    }

    public PriceCalendar(Date priceDate) {
       this.priceDate = priceDate;
    }
   
    public Date getPriceDate() {
        return this.priceDate;
    }
    
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }




}


