package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * Price generated by hbm2java
 */
public class Price  implements java.io.Serializable {


     private PriceId id;
     private PoLine poLine;
     private PriceCalendar priceCalendar;
     private Supplier supplier;
     private Double oringialPrice;
     private Double price;

    public Price() {
    }

	
    public Price(PriceId id, PoLine poLine, PriceCalendar priceCalendar, Supplier supplier) {
        this.id = id;
        this.poLine = poLine;
        this.priceCalendar = priceCalendar;
        this.supplier = supplier;
    }
    public Price(PriceId id, PoLine poLine, PriceCalendar priceCalendar, Supplier supplier, Double oringialPrice, Double price) {
       this.id = id;
       this.poLine = poLine;
       this.priceCalendar = priceCalendar;
       this.supplier = supplier;
       this.oringialPrice = oringialPrice;
       this.price = price;
    }
   
    public PriceId getId() {
        return this.id;
    }
    
    public void setId(PriceId id) {
        this.id = id;
    }
    public PoLine getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(PoLine poLine) {
        this.poLine = poLine;
    }
    public PriceCalendar getPriceCalendar() {
        return this.priceCalendar;
    }
    
    public void setPriceCalendar(PriceCalendar priceCalendar) {
        this.priceCalendar = priceCalendar;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Double getOringialPrice() {
        return this.oringialPrice;
    }
    
    public void setOringialPrice(Double oringialPrice) {
        this.oringialPrice = oringialPrice;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


