package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private int idPr;
     private String descriptionPr;
     private Set<AirsupplyUser> airsupplyUsers = new HashSet<AirsupplyUser>(0);

    public Privilege() {
    }

	
    public Privilege(int idPr) {
        this.idPr = idPr;
    }
    public Privilege(int idPr, String descriptionPr, Set<AirsupplyUser> airsupplyUsers) {
       this.idPr = idPr;
       this.descriptionPr = descriptionPr;
       this.airsupplyUsers = airsupplyUsers;
    }
   
    public int getIdPr() {
        return this.idPr;
    }
    
    public void setIdPr(int idPr) {
        this.idPr = idPr;
    }
    public String getDescriptionPr() {
        return this.descriptionPr;
    }
    
    public void setDescriptionPr(String descriptionPr) {
        this.descriptionPr = descriptionPr;
    }
    public Set<AirsupplyUser> getAirsupplyUsers() {
        return this.airsupplyUsers;
    }
    
    public void setAirsupplyUsers(Set<AirsupplyUser> airsupplyUsers) {
        this.airsupplyUsers = airsupplyUsers;
    }




}


