package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private int idPr;
     private String descriptionPr;

    public Privilege() {
    }

	
    public Privilege(int idPr) {
        this.idPr = idPr;
    }
    public Privilege(int idPr, String descriptionPr) {
       this.idPr = idPr;
       this.descriptionPr = descriptionPr;
    }
   
    public int getIdPr() {
        return this.idPr;
    }
    
    public void setIdPr(int idPr) {
        this.idPr = idPr;
    }
    public String getDescriptionPr() {
        return this.descriptionPr;
    }
    
    public void setDescriptionPr(String descriptionPr) {
        this.descriptionPr = descriptionPr;
    }




}


