package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * Promised generated by hbm2java
 */
public class Promised  implements java.io.Serializable {


     private PromisedId id;
     private PoLine poLine;
     private PromiseCalendar promiseCalendar;
     private Supplier supplier;
     private Integer quantityPromised;

    public Promised() {
    }

	
    public Promised(PromisedId id, PoLine poLine, PromiseCalendar promiseCalendar, Supplier supplier) {
        this.id = id;
        this.poLine = poLine;
        this.promiseCalendar = promiseCalendar;
        this.supplier = supplier;
    }
    public Promised(PromisedId id, PoLine poLine, PromiseCalendar promiseCalendar, Supplier supplier, Integer quantityPromised) {
       this.id = id;
       this.poLine = poLine;
       this.promiseCalendar = promiseCalendar;
       this.supplier = supplier;
       this.quantityPromised = quantityPromised;
    }
   
    public PromisedId getId() {
        return this.id;
    }
    
    public void setId(PromisedId id) {
        this.id = id;
    }
    public PoLine getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(PoLine poLine) {
        this.poLine = poLine;
    }
    public PromiseCalendar getPromiseCalendar() {
        return this.promiseCalendar;
    }
    
    public void setPromiseCalendar(PromiseCalendar promiseCalendar) {
        this.promiseCalendar = promiseCalendar;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Integer getQuantityPromised() {
        return this.quantityPromised;
    }
    
    public void setQuantityPromised(Integer quantityPromised) {
        this.quantityPromised = quantityPromised;
    }




}


