package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PromisedId generated by hbm2java
 */
public class PromisedId  implements java.io.Serializable {


     private String poLineId;
     private Date promisedDate;
     private String idS;

    public PromisedId() {
    }

    public PromisedId(String poLineId, Date promisedDate, String idS) {
       this.poLineId = poLineId;
       this.promisedDate = promisedDate;
       this.idS = idS;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public Date getPromisedDate() {
        return this.promisedDate;
    }
    
    public void setPromisedDate(Date promisedDate) {
        this.promisedDate = promisedDate;
    }
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PromisedId) ) return false;
		 PromisedId castOther = ( PromisedId ) other; 
         
		 return ( (this.getPoLineId()==castOther.getPoLineId()) || ( this.getPoLineId()!=null && castOther.getPoLineId()!=null && this.getPoLineId().equals(castOther.getPoLineId()) ) )
 && ( (this.getPromisedDate()==castOther.getPromisedDate()) || ( this.getPromisedDate()!=null && castOther.getPromisedDate()!=null && this.getPromisedDate().equals(castOther.getPromisedDate()) ) )
 && ( (this.getIdS()==castOther.getIdS()) || ( this.getIdS()!=null && castOther.getIdS()!=null && this.getIdS().equals(castOther.getIdS()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPoLineId() == null ? 0 : this.getPoLineId().hashCode() );
         result = 37 * result + ( getPromisedDate() == null ? 0 : this.getPromisedDate().hashCode() );
         result = 37 * result + ( getIdS() == null ? 0 : this.getIdS().hashCode() );
         return result;
   }   


}


