package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PromiseCalendar generated by hbm2java
 */
public class PromiseCalendar  implements java.io.Serializable {


     private Date promisedDate;

    public PromiseCalendar() {
    }

    public PromiseCalendar(Date promisedDate) {
       this.promisedDate = promisedDate;
    }
   
    public Date getPromisedDate() {
        return this.promisedDate;
    }
    
    public void setPromisedDate(Date promisedDate) {
        this.promisedDate = promisedDate;
    }




}


