package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PromiseCalendar generated by hbm2java
 */
public class PromiseCalendar  implements java.io.Serializable {


     private Date promisedDate;
     private Set<Promised> promiseds = new HashSet<Promised>(0);

    public PromiseCalendar() {
    }

	
    public PromiseCalendar(Date promisedDate) {
        this.promisedDate = promisedDate;
    }
    public PromiseCalendar(Date promisedDate, Set<Promised> promiseds) {
       this.promisedDate = promisedDate;
       this.promiseds = promiseds;
    }
   
    public Date getPromisedDate() {
        return this.promisedDate;
    }
    
    public void setPromisedDate(Date promisedDate) {
        this.promisedDate = promisedDate;
    }
    public Set<Promised> getPromiseds() {
        return this.promiseds;
    }
    
    public void setPromiseds(Set<Promised> promiseds) {
        this.promiseds = promiseds;
    }




}


