package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Promised generated by hbm2java
 */
public class Promised  implements java.io.Serializable {


     private PromisedId id;
     private Integer quantityPromised;

    public Promised() {
    }

	
    public Promised(PromisedId id) {
        this.id = id;
    }
    public Promised(PromisedId id, Integer quantityPromised) {
       this.id = id;
       this.quantityPromised = quantityPromised;
    }
   
    public PromisedId getId() {
        return this.id;
    }
    
    public void setId(PromisedId id) {
        this.id = id;
    }
    public Integer getQuantityPromised() {
        return this.quantityPromised;
    }
    
    public void setQuantityPromised(Integer quantityPromised) {
        this.quantityPromised = quantityPromised;
    }




}


