package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * Received generated by hbm2java
 */
public class Received  implements java.io.Serializable {


     private ReceivedId id;
     private PoLine poLine;
     private Supplier supplier;
     private Integer receivedQuantity;

    public Received() {
    }

	
    public Received(ReceivedId id, PoLine poLine, Supplier supplier) {
        this.id = id;
        this.poLine = poLine;
        this.supplier = supplier;
    }
    public Received(ReceivedId id, PoLine poLine, Supplier supplier, Integer receivedQuantity) {
       this.id = id;
       this.poLine = poLine;
       this.supplier = supplier;
       this.receivedQuantity = receivedQuantity;
    }
   
    public ReceivedId getId() {
        return this.id;
    }
    
    public void setId(ReceivedId id) {
        this.id = id;
    }
    public PoLine getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(PoLine poLine) {
        this.poLine = poLine;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Integer getReceivedQuantity() {
        return this.receivedQuantity;
    }
    
    public void setReceivedQuantity(Integer receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }




}


