package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * ReceivedId generated by hbm2java
 */
public class ReceivedId  implements java.io.Serializable {


     private String idS;
     private String poLineId;

    public ReceivedId() {
    }

    public ReceivedId(String idS, String poLineId) {
       this.idS = idS;
       this.poLineId = poLineId;
    }
   
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReceivedId) ) return false;
		 ReceivedId castOther = ( ReceivedId ) other; 
         
		 return ( (this.getIdS()==castOther.getIdS()) || ( this.getIdS()!=null && castOther.getIdS()!=null && this.getIdS().equals(castOther.getIdS()) ) )
 && ( (this.getPoLineId()==castOther.getPoLineId()) || ( this.getPoLineId()!=null && castOther.getPoLineId()!=null && this.getPoLineId().equals(castOther.getPoLineId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdS() == null ? 0 : this.getIdS().hashCode() );
         result = 37 * result + ( getPoLineId() == null ? 0 : this.getPoLineId().hashCode() );
         return result;
   }   


}


