package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Received generated by hbm2java
 */
public class Received  implements java.io.Serializable {


     private ReceivedId id;
     private Integer receivedQuantity;

    public Received() {
    }

	
    public Received(ReceivedId id) {
        this.id = id;
    }
    public Received(ReceivedId id, Integer receivedQuantity) {
       this.id = id;
       this.receivedQuantity = receivedQuantity;
    }
   
    public ReceivedId getId() {
        return this.id;
    }
    
    public void setId(ReceivedId id) {
        this.id = id;
    }
    public Integer getReceivedQuantity() {
        return this.receivedQuantity;
    }
    
    public void setReceivedQuantity(Integer receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }




}


