package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Requested generated by hbm2java
 */
public class Requested  implements java.io.Serializable {


     private RequestedId id;
     private Integer requestedQuantity;

    public Requested() {
    }

	
    public Requested(RequestedId id) {
        this.id = id;
    }
    public Requested(RequestedId id, Integer requestedQuantity) {
       this.id = id;
       this.requestedQuantity = requestedQuantity;
    }
   
    public RequestedId getId() {
        return this.id;
    }
    
    public void setId(RequestedId id) {
        this.id = id;
    }
    public Integer getRequestedQuantity() {
        return this.requestedQuantity;
    }
    
    public void setRequestedQuantity(Integer requestedQuantity) {
        this.requestedQuantity = requestedQuantity;
    }




}


