package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RequestedCalendar generated by hbm2java
 */
public class RequestedCalendar  implements java.io.Serializable {


     private Date requestedDate;

    public RequestedCalendar() {
    }

    public RequestedCalendar(Date requestedDate) {
       this.requestedDate = requestedDate;
    }
   
    public Date getRequestedDate() {
        return this.requestedDate;
    }
    
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }




}


