package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * Requested generated by hbm2java
 */
public class Requested  implements java.io.Serializable {


     private RequestedId id;
     private PoLine poLine;
     private RequestedCalendar requestedCalendar;
     private Supplier supplier;
     private Integer requestedQuantity;

    public Requested() {
    }

	
    public Requested(RequestedId id, PoLine poLine, RequestedCalendar requestedCalendar, Supplier supplier) {
        this.id = id;
        this.poLine = poLine;
        this.requestedCalendar = requestedCalendar;
        this.supplier = supplier;
    }
    public Requested(RequestedId id, PoLine poLine, RequestedCalendar requestedCalendar, Supplier supplier, Integer requestedQuantity) {
       this.id = id;
       this.poLine = poLine;
       this.requestedCalendar = requestedCalendar;
       this.supplier = supplier;
       this.requestedQuantity = requestedQuantity;
    }
   
    public RequestedId getId() {
        return this.id;
    }
    
    public void setId(RequestedId id) {
        this.id = id;
    }
    public PoLine getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(PoLine poLine) {
        this.poLine = poLine;
    }
    public RequestedCalendar getRequestedCalendar() {
        return this.requestedCalendar;
    }
    
    public void setRequestedCalendar(RequestedCalendar requestedCalendar) {
        this.requestedCalendar = requestedCalendar;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Integer getRequestedQuantity() {
        return this.requestedQuantity;
    }
    
    public void setRequestedQuantity(Integer requestedQuantity) {
        this.requestedQuantity = requestedQuantity;
    }




}


