package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RequestedId generated by hbm2java
 */
public class RequestedId  implements java.io.Serializable {


     private String poLineId;
     private Date requestedDate;
     private String idS;

    public RequestedId() {
    }

    public RequestedId(String poLineId, Date requestedDate, String idS) {
       this.poLineId = poLineId;
       this.requestedDate = requestedDate;
       this.idS = idS;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public Date getRequestedDate() {
        return this.requestedDate;
    }
    
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RequestedId) ) return false;
		 RequestedId castOther = ( RequestedId ) other; 
         
		 return ( (this.getPoLineId()==castOther.getPoLineId()) || ( this.getPoLineId()!=null && castOther.getPoLineId()!=null && this.getPoLineId().equals(castOther.getPoLineId()) ) )
 && ( (this.getRequestedDate()==castOther.getRequestedDate()) || ( this.getRequestedDate()!=null && castOther.getRequestedDate()!=null && this.getRequestedDate().equals(castOther.getRequestedDate()) ) )
 && ( (this.getIdS()==castOther.getIdS()) || ( this.getIdS()!=null && castOther.getIdS()!=null && this.getIdS().equals(castOther.getIdS()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPoLineId() == null ? 0 : this.getPoLineId().hashCode() );
         result = 37 * result + ( getRequestedDate() == null ? 0 : this.getRequestedDate().hashCode() );
         result = 37 * result + ( getIdS() == null ? 0 : this.getIdS().hashCode() );
         return result;
   }   


}


