package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RequestedCalendar generated by hbm2java
 */
public class RequestedCalendar  implements java.io.Serializable {


     private Date requestedDate;
     private Set<Requested> requesteds = new HashSet<Requested>(0);

    public RequestedCalendar() {
    }

	
    public RequestedCalendar(Date requestedDate) {
        this.requestedDate = requestedDate;
    }
    public RequestedCalendar(Date requestedDate, Set<Requested> requesteds) {
       this.requestedDate = requestedDate;
       this.requesteds = requesteds;
    }
   
    public Date getRequestedDate() {
        return this.requestedDate;
    }
    
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }
    public Set<Requested> getRequesteds() {
        return this.requesteds;
    }
    
    public void setRequesteds(Set<Requested> requesteds) {
        this.requesteds = requesteds;
    }




}


