package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int idStatus;
     private String descriptionSatus;
     private Set<HasA> hasAs = new HashSet<HasA>(0);

    public Status() {
    }

	
    public Status(int idStatus) {
        this.idStatus = idStatus;
    }
    public Status(int idStatus, String descriptionSatus, Set<HasA> hasAs) {
       this.idStatus = idStatus;
       this.descriptionSatus = descriptionSatus;
       this.hasAs = hasAs;
    }
   
    public int getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }
    public String getDescriptionSatus() {
        return this.descriptionSatus;
    }
    
    public void setDescriptionSatus(String descriptionSatus) {
        this.descriptionSatus = descriptionSatus;
    }
    public Set<HasA> getHasAs() {
        return this.hasAs;
    }
    
    public void setHasAs(Set<HasA> hasAs) {
        this.hasAs = hasAs;
    }




}


