package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int idStatus;
     private String descriptionSatus;

    public Status() {
    }

	
    public Status(int idStatus) {
        this.idStatus = idStatus;
    }
    public Status(int idStatus, String descriptionSatus) {
       this.idStatus = idStatus;
       this.descriptionSatus = descriptionSatus;
    }
   
    public int getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }
    public String getDescriptionSatus() {
        return this.descriptionSatus;
    }
    
    public void setDescriptionSatus(String descriptionSatus) {
        this.descriptionSatus = descriptionSatus;
    }




}


