package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StockUpdateDate generated by hbm2java
 */
public class StockUpdateDate  implements java.io.Serializable {


     private Date updateDate;
     private Set<MaterialVmi2> materialVmi2s = new HashSet<MaterialVmi2>(0);

    public StockUpdateDate() {
    }

	
    public StockUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public StockUpdateDate(Date updateDate, Set<MaterialVmi2> materialVmi2s) {
       this.updateDate = updateDate;
       this.materialVmi2s = materialVmi2s;
    }
   
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Set<MaterialVmi2> getMaterialVmi2s() {
        return this.materialVmi2s;
    }
    
    public void setMaterialVmi2s(Set<MaterialVmi2> materialVmi2s) {
        this.materialVmi2s = materialVmi2s;
    }




}


