package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StockUpdateDate generated by hbm2java
 */
public class StockUpdateDate  implements java.io.Serializable {


     private Date updateDate;

    public StockUpdateDate() {
    }

    public StockUpdateDate(Date updateDate) {
       this.updateDate = updateDate;
    }
   
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


