package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private String idS;
     private String nameS;
     private String streetS;
     private String zipS;
     private String cityS;
     private String countrycodeS;

    public Supplier() {
    }

	
    public Supplier(String idS) {
        this.idS = idS;
    }
    public Supplier(String idS, String nameS, String streetS, String zipS, String cityS, String countrycodeS) {
       this.idS = idS;
       this.nameS = nameS;
       this.streetS = streetS;
       this.zipS = zipS;
       this.cityS = cityS;
       this.countrycodeS = countrycodeS;
    }
   
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }
    public String getNameS() {
        return this.nameS;
    }
    
    public void setNameS(String nameS) {
        this.nameS = nameS;
    }
    public String getStreetS() {
        return this.streetS;
    }
    
    public void setStreetS(String streetS) {
        this.streetS = streetS;
    }
    public String getZipS() {
        return this.zipS;
    }
    
    public void setZipS(String zipS) {
        this.zipS = zipS;
    }
    public String getCityS() {
        return this.cityS;
    }
    
    public void setCityS(String cityS) {
        this.cityS = cityS;
    }
    public String getCountrycodeS() {
        return this.countrycodeS;
    }
    
    public void setCountrycodeS(String countrycodeS) {
        this.countrycodeS = countrycodeS;
    }




}


