package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private String idS;
     private String nameS;
     private String streetS;
     private String zipS;
     private String cityS;
     private String countrycodeS;
     private Set<SupplySite> supplySites = new HashSet<SupplySite>(0);
     private Set<MaterialVmi2> materialVmi2s = new HashSet<MaterialVmi2>(0);
     private Set<Price> prices = new HashSet<Price>(0);
     private Set<Promised> promiseds = new HashSet<Promised>(0);
     private Set<Received> receiveds = new HashSet<Received>(0);
     private Set<AirsupplyUser> airsupplyUsers = new HashSet<AirsupplyUser>(0);
     private Set<Requested> requesteds = new HashSet<Requested>(0);
     private Set<Alert> alerts = new HashSet<Alert>(0);

    public Supplier() {
    }

	
    public Supplier(String idS) {
        this.idS = idS;
    }
    public Supplier(String idS, String nameS, String streetS, String zipS, String cityS, String countrycodeS, Set<SupplySite> supplySites, Set<MaterialVmi2> materialVmi2s, Set<Price> prices, Set<Promised> promiseds, Set<Received> receiveds, Set<AirsupplyUser> airsupplyUsers, Set<Requested> requesteds, Set<Alert> alerts) {
       this.idS = idS;
       this.nameS = nameS;
       this.streetS = streetS;
       this.zipS = zipS;
       this.cityS = cityS;
       this.countrycodeS = countrycodeS;
       this.supplySites = supplySites;
       this.materialVmi2s = materialVmi2s;
       this.prices = prices;
       this.promiseds = promiseds;
       this.receiveds = receiveds;
       this.airsupplyUsers = airsupplyUsers;
       this.requesteds = requesteds;
       this.alerts = alerts;
    }
   
    public String getIdS() {
        return this.idS;
    }
    
    public void setIdS(String idS) {
        this.idS = idS;
    }
    public String getNameS() {
        return this.nameS;
    }
    
    public void setNameS(String nameS) {
        this.nameS = nameS;
    }
    public String getStreetS() {
        return this.streetS;
    }
    
    public void setStreetS(String streetS) {
        this.streetS = streetS;
    }
    public String getZipS() {
        return this.zipS;
    }
    
    public void setZipS(String zipS) {
        this.zipS = zipS;
    }
    public String getCityS() {
        return this.cityS;
    }
    
    public void setCityS(String cityS) {
        this.cityS = cityS;
    }
    public String getCountrycodeS() {
        return this.countrycodeS;
    }
    
    public void setCountrycodeS(String countrycodeS) {
        this.countrycodeS = countrycodeS;
    }
    public Set<SupplySite> getSupplySites() {
        return this.supplySites;
    }
    
    public void setSupplySites(Set<SupplySite> supplySites) {
        this.supplySites = supplySites;
    }
    public Set<MaterialVmi2> getMaterialVmi2s() {
        return this.materialVmi2s;
    }
    
    public void setMaterialVmi2s(Set<MaterialVmi2> materialVmi2s) {
        this.materialVmi2s = materialVmi2s;
    }
    public Set<Price> getPrices() {
        return this.prices;
    }
    
    public void setPrices(Set<Price> prices) {
        this.prices = prices;
    }
    public Set<Promised> getPromiseds() {
        return this.promiseds;
    }
    
    public void setPromiseds(Set<Promised> promiseds) {
        this.promiseds = promiseds;
    }
    public Set<Received> getReceiveds() {
        return this.receiveds;
    }
    
    public void setReceiveds(Set<Received> receiveds) {
        this.receiveds = receiveds;
    }
    public Set<AirsupplyUser> getAirsupplyUsers() {
        return this.airsupplyUsers;
    }
    
    public void setAirsupplyUsers(Set<AirsupplyUser> airsupplyUsers) {
        this.airsupplyUsers = airsupplyUsers;
    }
    public Set<Requested> getRequesteds() {
        return this.requesteds;
    }
    
    public void setRequesteds(Set<Requested> requesteds) {
        this.requesteds = requesteds;
    }
    public Set<Alert> getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set<Alert> alerts) {
        this.alerts = alerts;
    }




}


