package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1



/**
 * SupplySite generated by hbm2java
 */
public class SupplySite  implements java.io.Serializable {


     private Integer idSypplySite;
     private Supplier supplier;
     private String supplierSiteCity;

    public SupplySite() {
    }

	
    public SupplySite(Supplier supplier) {
        this.supplier = supplier;
    }
    public SupplySite(Supplier supplier, String supplierSiteCity) {
       this.supplier = supplier;
       this.supplierSiteCity = supplierSiteCity;
    }
   
    public Integer getIdSypplySite() {
        return this.idSypplySite;
    }
    
    public void setIdSypplySite(Integer idSypplySite) {
        this.idSypplySite = idSypplySite;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getSupplierSiteCity() {
        return this.supplierSiteCity;
    }
    
    public void setSupplierSiteCity(String supplierSiteCity) {
        this.supplierSiteCity = supplierSiteCity;
    }




}


