package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * ToBeAlert generated by hbm2java
 */
public class ToBeAlert  implements java.io.Serializable {


     private ToBeAlertId id;

    public ToBeAlert() {
    }

    public ToBeAlert(ToBeAlertId id) {
       this.id = id;
    }
   
    public ToBeAlertId getId() {
        return this.id;
    }
    
    public void setId(ToBeAlertId id) {
        this.id = id;
    }




}


