package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ToBeAlertId generated by hbm2java
 */
public class ToBeAlertId  implements java.io.Serializable {


     private String poLineId;
     private int idAlert;
     private Date dateAlert;

    public ToBeAlertId() {
    }

    public ToBeAlertId(String poLineId, int idAlert, Date dateAlert) {
       this.poLineId = poLineId;
       this.idAlert = idAlert;
       this.dateAlert = dateAlert;
    }
   
    public String getPoLineId() {
        return this.poLineId;
    }
    
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
    public int getIdAlert() {
        return this.idAlert;
    }
    
    public void setIdAlert(int idAlert) {
        this.idAlert = idAlert;
    }
    public Date getDateAlert() {
        return this.dateAlert;
    }
    
    public void setDateAlert(Date dateAlert) {
        this.dateAlert = dateAlert;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ToBeAlertId) ) return false;
		 ToBeAlertId castOther = ( ToBeAlertId ) other; 
         
		 return ( (this.getPoLineId()==castOther.getPoLineId()) || ( this.getPoLineId()!=null && castOther.getPoLineId()!=null && this.getPoLineId().equals(castOther.getPoLineId()) ) )
 && (this.getIdAlert()==castOther.getIdAlert())
 && ( (this.getDateAlert()==castOther.getDateAlert()) || ( this.getDateAlert()!=null && castOther.getDateAlert()!=null && this.getDateAlert().equals(castOther.getDateAlert()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPoLineId() == null ? 0 : this.getPoLineId().hashCode() );
         result = 37 * result + this.getIdAlert();
         result = 37 * result + ( getDateAlert() == null ? 0 : this.getDateAlert().hashCode() );
         return result;
   }   


}


