package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vmi generated by hbm2java
 */
public class Vmi  implements java.io.Serializable {


     private String referenceNumber;
     private String processKey;
     private Date dateCreationVmi;

    public Vmi() {
    }

	
    public Vmi(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }
    public Vmi(String referenceNumber, String processKey, Date dateCreationVmi) {
       this.referenceNumber = referenceNumber;
       this.processKey = processKey;
       this.dateCreationVmi = dateCreationVmi;
    }
   
    public String getReferenceNumber() {
        return this.referenceNumber;
    }
    
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }
    public String getProcessKey() {
        return this.processKey;
    }
    
    public void setProcessKey(String processKey) {
        this.processKey = processKey;
    }
    public Date getDateCreationVmi() {
        return this.dateCreationVmi;
    }
    
    public void setDateCreationVmi(Date dateCreationVmi) {
        this.dateCreationVmi = dateCreationVmi;
    }




}


