package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vmi generated by hbm2java
 */
public class Vmi  implements java.io.Serializable {


     private String referenceNumber;
     private String processKey;
     private Date dateCreationVmi;
     private Set<VmiItem> vmiItems = new HashSet<VmiItem>(0);

    public Vmi() {
    }

	
    public Vmi(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }
    public Vmi(String referenceNumber, String processKey, Date dateCreationVmi, Set<VmiItem> vmiItems) {
       this.referenceNumber = referenceNumber;
       this.processKey = processKey;
       this.dateCreationVmi = dateCreationVmi;
       this.vmiItems = vmiItems;
    }
   
    public String getReferenceNumber() {
        return this.referenceNumber;
    }
    
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }
    public String getProcessKey() {
        return this.processKey;
    }
    
    public void setProcessKey(String processKey) {
        this.processKey = processKey;
    }
    public Date getDateCreationVmi() {
        return this.dateCreationVmi;
    }
    
    public void setDateCreationVmi(Date dateCreationVmi) {
        this.dateCreationVmi = dateCreationVmi;
    }
    public Set<VmiItem> getVmiItems() {
        return this.vmiItems;
    }
    
    public void setVmiItems(Set<VmiItem> vmiItems) {
        this.vmiItems = vmiItems;
    }




}


