package DataBase_Objects;
// Generated 22 mars 2017 17:41:26 by Hibernate Tools 4.3.1



/**
 * VmiItem generated by hbm2java
 */
public class VmiItem  implements java.io.Serializable {


     private String referenceItem;
     private String referenceNumber;

    public VmiItem() {
    }

    public VmiItem(String referenceItem, String referenceNumber) {
       this.referenceItem = referenceItem;
       this.referenceNumber = referenceNumber;
    }
   
    public String getReferenceItem() {
        return this.referenceItem;
    }
    
    public void setReferenceItem(String referenceItem) {
        this.referenceItem = referenceItem;
    }
    public String getReferenceNumber() {
        return this.referenceNumber;
    }
    
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }




}


