package DataBase_Objects;
// Generated 23 mars 2017 11:13:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VmiItem generated by hbm2java
 */
public class VmiItem  implements java.io.Serializable {


     private String referenceItem;
     private Vmi vmi;
     private Set<MaterialVmi2> materialVmi2s = new HashSet<MaterialVmi2>(0);

    public VmiItem() {
    }

	
    public VmiItem(String referenceItem, Vmi vmi) {
        this.referenceItem = referenceItem;
        this.vmi = vmi;
    }
    public VmiItem(String referenceItem, Vmi vmi, Set<MaterialVmi2> materialVmi2s) {
       this.referenceItem = referenceItem;
       this.vmi = vmi;
       this.materialVmi2s = materialVmi2s;
    }
   
    public String getReferenceItem() {
        return this.referenceItem;
    }
    
    public void setReferenceItem(String referenceItem) {
        this.referenceItem = referenceItem;
    }
    public Vmi getVmi() {
        return this.vmi;
    }
    
    public void setVmi(Vmi vmi) {
        this.vmi = vmi;
    }
    public Set<MaterialVmi2> getMaterialVmi2s() {
        return this.materialVmi2s;
    }
    
    public void setMaterialVmi2s(Set<MaterialVmi2> materialVmi2s) {
        this.materialVmi2s = materialVmi2s;
    }




}


